import {ActivityIndicator,StyleSheet,View} from 'react-native';
import {Redirect,Tabs} from 'expo-router';
import {Ionicons} from '@expo/vector-icons';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {APP_CONFIG} from '@/config/app';
import {useSession} from '@/lib/session';
import {typography,useTheme} from '@/lib/theme';
const icons:any={index:'grid-outline',transactions:'swap-horizontal-outline',invoices:'document-text-outline',contacts:'people-outline',more:'ellipsis-horizontal-circle-outline'};
export default function TabsLayout(){const{colors}=useTheme();const{token,loading}=useSession();const insets=useSafeAreaInsets();const base=APP_CONFIG.layout.tabBarBaseHeight;if(loading)return <View style={{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:colors.background}}><ActivityIndicator color={colors.primary}/></View>;if(!token)return <Redirect href="/(auth)/login"/>;return <Tabs screenOptions={({route})=>({headerShown:false,tabBarActiveTintColor:colors.primary,tabBarInactiveTintColor:colors.textSoft,tabBarStyle:{height:base+Math.max(insets.bottom,8),paddingBottom:Math.max(insets.bottom,8),paddingTop:7,borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:colors.border,backgroundColor:colors.tab},tabBarLabelStyle:{fontSize:10,...typography.medium},tabBarIcon:({color,size})=><Ionicons name={icons[route.name]||'ellipse-outline'} color={color} size={Math.min(size,23)}/>})}><Tabs.Screen name="index" options={{title:APP_CONFIG.navigation.overview}}/><Tabs.Screen name="transactions" options={{title:APP_CONFIG.navigation.money}}/><Tabs.Screen name="invoices" options={{title:APP_CONFIG.navigation.invoices}}/><Tabs.Screen name="contacts" options={{title:APP_CONFIG.navigation.contacts}}/><Tabs.Screen name="more" options={{title:APP_CONFIG.navigation.workspace}}/></Tabs>}
