import {useCallback,useState} from 'react';
import {Alert,StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import {FormScrollView} from '@/components/FormScrollView';
import {useFocusEffect} from 'expo-router';
import {Ionicons} from '@expo/vector-icons';
import {api} from '@/lib/api';
import {APP_CONFIG} from '@/config/app';
import {useTheme} from '@/lib/theme';
import {AppBackground,Button,ChoiceChips,DetailModal,EmptyState,Field,GlassCard,InfoRow,Money,Notice,Pill,ScreenHeader,useResponsivePage} from '@/components/UI';
import {useSession} from '@/lib/session';

export default function Contacts(){
  const[list,setList]=useState<any[]>([]),[show,setShow]=useState(false),[type,setType]=useState<'CUSTOMER'|'SUPPLIER'>('CUSTOMER'),[name,setName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[address,setAddress]=useState(''),[trn,setTrn]=useState(''),[notes,setNotes]=useState(''),[selected,setSelected]=useState<any>(null),[statement,setStatement]=useState<any>(null),[loadingDetail,setLoadingDetail]=useState(false),[filter,setFilter]=useState('ALL'),[loadError,setLoadError]=useState('');
  const{user}=useSession();const{colors}=useTheme();const page=useResponsivePage(true);const load=async()=>{try{setList(await api('/parties'));setLoadError('')}catch(error:any){setLoadError(error?.message||'Contacts could not be loaded.')}};useFocusEffect(useCallback(()=>{void load()},[]));
  async function save(){if(!name.trim())return Alert.alert('Name required');try{await api('/parties',{method:'POST',headers:{'Idempotency-Key':`${Date.now()}-${Math.random()}`},body:JSON.stringify({type,name,email,phone,address,trn,notes})});setShow(false);setName('');setEmail('');setPhone('');setAddress('');setTrn('');setNotes('');await load()}catch(e:any){Alert.alert('Could not save contact',e.message)}}
  async function open(x:any){setSelected(x);setStatement(null);setLoadingDetail(true);try{setStatement(await api(`/reports/customer/${x._id}/statement`))}catch{}finally{setLoadingDetail(false)}}
  async function remove(x:any){Alert.alert(`Delete ${x.type==='CUSTOMER'?'customer':'supplier'}`,`Delete ${x.name}? Existing transactions and invoices remain as historical records.`,[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:async()=>{try{await api(`/parties/${x._id}`,{method:'DELETE',headers:{'Idempotency-Key':`${Date.now()}-${Math.random()}`}});setSelected(null);await load()}catch(e:any){Alert.alert('Delete failed',e.message)}}}])}
  const currency=user?.business?.currency||APP_CONFIG.businessDefaults.currency;const shown=filter==='ALL'?list:list.filter(x=>x.type===filter);const customers=list.filter(x=>x.type==='CUSTOMER').length,suppliers=list.filter(x=>x.type==='SUPPLIER').length;
  return <AppBackground><FormScrollView style={{flex:1}} contentContainerStyle={[s.content,page]} keyboardShouldPersistTaps="handled">
    <ScreenHeader title={APP_CONFIG.copy.contactsTitle} subtitle={APP_CONFIG.copy.contactsSubtitle} right={<TouchableOpacity style={[s.add,{backgroundColor:colors.primary}]} onPress={()=>setShow(!show)}><Ionicons name={show?'close':'add'} size={25} color={colors.onPrimary}/></TouchableOpacity>}/>
    {loadError?<View style={{marginBottom:12}}><Notice tone="danger" title="Contacts unavailable" body={loadError}/></View>:null}
    <View style={s.summary}><GlassCard style={s.sum}><Text style={[s.sumNum,{color:colors.text}]}>{customers}</Text><Text style={[s.sumLabel,{color:colors.textMuted}]}>Customers</Text></GlassCard><GlassCard style={s.sum}><Text style={[s.sumNum,{color:colors.text}]}>{suppliers}</Text><Text style={[s.sumLabel,{color:colors.textMuted}]}>Suppliers</Text></GlassCard></View>
    {show&&<GlassCard style={{gap:13,marginBottom:16}}><ChoiceChips options={[{key:'CUSTOMER',label:'Customer'},{key:'SUPPLIER',label:'Supplier'}]} value={type} onChange={v=>setType(v as any)}/><Field label="Name" value={name} onChangeText={setName}/><Field label="Email (optional)" value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address"/><Field label="Phone (optional)" value={phone} onChangeText={setPhone} keyboardType="phone-pad"/><Field label="Address (optional)" value={address} onChangeText={setAddress} multiline/><Field label="TRN (optional)" value={trn} onChangeText={setTrn}/><Field label="Notes (optional)" value={notes} onChangeText={setNotes} multiline/><Button title={`Add ${type==='CUSTOMER'?'customer':'supplier'}`} onPress={save}/></GlassCard>}
    <View style={s.filters}>{['ALL','CUSTOMER','SUPPLIER'].map(x=><Filter key={x} text={x==='ALL'?'All':x==='CUSTOMER'?'Customers':'Suppliers'} active={filter===x} onPress={()=>setFilter(x)}/>)}</View>
    <GlassCard>{shown.length?shown.map((x,i)=><TouchableOpacity key={x._id} onPress={()=>open(x)} activeOpacity={.72} style={[s.item,i>0?{borderTopWidth:1,borderTopColor:colors.border}:undefined]}><View style={[s.avatar,{backgroundColor:colors.accentSoft}]}><Text style={[s.initial,{color:colors.primary}]}>{x.name?.[0]?.toUpperCase()}</Text></View><View style={{flex:1,minWidth:0}}><View style={{flexDirection:'row',gap:7,alignItems:'center',flexWrap:'wrap'}}><Text numberOfLines={2} style={[s.name,{color:colors.text}]}>{x.name}</Text><Pill text={x.type==='CUSTOMER'?'Customer':'Supplier'} tone={x.type==='CUSTOMER'?'green':'blue'}/></View><Text style={[s.meta,{color:colors.textMuted}]}>{x.email||x.phone||'No contact info'}</Text><Text style={[s.stats,{color:colors.textMuted}]}>Business {currency} {Number(x.totalBusiness||0).toFixed(2)} • Outstanding {currency} {Number(x.outstanding||0).toFixed(2)}</Text></View><Ionicons name="chevron-forward" size={17} color={colors.textSoft}/></TouchableOpacity>):<EmptyState icon="people-outline" title="No contacts yet" body="Add customers and suppliers to connect invoices and transactions."/>}</GlassCard>
  </FormScrollView>
  <DetailModal visible={!!selected} onClose={()=>setSelected(null)} title={selected?.name||'Contact'} subtitle={selected?.type==='CUSTOMER'?'Customer account':'Supplier account'} footer={selected?<Button danger secondary icon="trash-outline" title="Delete contact" onPress={()=>remove(selected)} compact/>:undefined}>
    {selected?<><View style={[s.personHero,{backgroundColor:colors.accentSoft}]}><View style={[s.avatarLarge,{backgroundColor:colors.primary}]}><Text style={[s.initialLarge,{color:colors.onPrimary}]}>{selected.name?.[0]?.toUpperCase()}</Text></View><View style={{flex:1}}><Text style={[s.heroName,{color:colors.text}]}>{selected.name}</Text><Pill text={selected.type==='CUSTOMER'?'Customer':'Supplier'} tone={selected.type==='CUSTOMER'?'green':'blue'}/></View></View><InfoRow label="Email" value={selected.email||'—'}/><InfoRow label="Phone" value={selected.phone||'—'}/><InfoRow label="TRN" value={selected.trn||'—'}/><InfoRow label="Address" value={selected.address||'—'}/><InfoRow label="Total business" value={<Money value={selected.totalBusiness||0} currency={currency} size="sm"/>}/><InfoRow label="Outstanding" value={<Money value={selected.outstanding||0} currency={currency} size="sm" tone={selected.outstanding>0?'expense':'default'}/>} strong/><InfoRow label="Notes" value={selected.notes||'—'}/><Text style={[s.section,{color:colors.text}]}>Recent account activity</Text>{loadingDetail?<Text style={{color:colors.textMuted}}>Loading statement…</Text>:statement?(statement.invoices?.length||statement.transactions?.length)?<>{(statement.invoices||[]).slice(0,4).map((x:any)=><View key={x._id} style={[s.activity,{borderBottomColor:colors.border}]}><Ionicons name="document-text-outline" size={18} color={colors.primary}/><View style={{flex:1}}><Text style={{fontWeight:'500',fontSize:12,color:colors.text}}>{x.invoiceNumber}</Text><Text style={{fontSize:10,color:colors.textMuted}}>{new Date(x.issueDate).toLocaleDateString()} • {x.status}</Text></View><Money value={x.balance} currency={currency} size="sm"/></View>)}{(statement.transactions||[]).slice(0,5).map((x:any)=><View key={x._id} style={[s.activity,{borderBottomColor:colors.border}]}><Ionicons name={x.type==='INCOME'?'arrow-down':'arrow-up'} size={18} color={x.type==='INCOME'?colors.success:colors.danger}/><View style={{flex:1}}><Text style={{fontWeight:'500',fontSize:12,color:colors.text}}>{x.category}</Text><Text style={{fontSize:10,color:colors.textMuted}}>{new Date(x.date).toLocaleDateString()} • {x.paymentMethod}</Text></View><Money value={x.amount} currency={currency} size="sm" tone={x.type==='INCOME'?'income':'expense'}/></View>)}</>:<Text style={{color:colors.textMuted}}>No account activity yet.</Text>:null}</>:null}
  </DetailModal>
  </AppBackground>
}
function Filter({text,active,onPress}:{text:string;active:boolean;onPress:()=>void}){const{colors}=useTheme();return <TouchableOpacity onPress={onPress} style={[s.filter,{backgroundColor:active?colors.primary:colors.surfaceStrong,borderColor:active?colors.primary:colors.border}]}><Text style={{fontSize:11,fontWeight:'500',color:active?colors.onPrimary:colors.textMuted}}>{text}</Text></TouchableOpacity>}
const s=StyleSheet.create({content:{padding:20,paddingTop:58,paddingBottom:118},add:{width:46,height:46,borderRadius:16,alignItems:'center',justifyContent:'center'},summary:{flexDirection:'row',gap:12,marginBottom:14},sum:{flex:1,minHeight:82,justifyContent:'space-between'},sumNum:{fontSize:24,fontWeight:'500'},sumLabel:{fontSize:11,fontWeight:'500'},filters:{flexDirection:'row',flexWrap:'wrap',gap:8,marginBottom:12},filter:{borderWidth:1,borderRadius:999,paddingHorizontal:13,paddingVertical:8},item:{flexDirection:'row',gap:12,alignItems:'center',paddingVertical:15},avatar:{width:46,height:46,borderRadius:16,alignItems:'center',justifyContent:'center'},initial:{fontWeight:'500',fontSize:18},name:{fontWeight:'500',fontSize:14,flexShrink:1},meta:{fontSize:11,marginTop:5},stats:{fontSize:10,marginTop:5},personHero:{borderRadius:20,padding:16,flexDirection:'row',alignItems:'center',gap:12,marginBottom:10},avatarLarge:{width:58,height:58,borderRadius:19,alignItems:'center',justifyContent:'center'},initialLarge:{fontWeight:'500',fontSize:23},heroName:{fontWeight:'500',fontSize:18,marginBottom:6},section:{fontSize:14,fontWeight:'500',marginTop:20,marginBottom:7},activity:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:11,borderBottomWidth:1}});
