import {useCallback,useMemo,useState} from 'react';
import {RefreshControl,ScrollView,StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import {router,useFocusEffect} from 'expo-router';
import {Ionicons} from '@expo/vector-icons';
import {api} from '@/lib/api';
import {useSession} from '@/lib/session';
import {APP_CONFIG} from '@/config/app';
import {typography,useTheme} from '@/lib/theme';
import {SmartImage} from '@/components/Media';
import {AppBackground,GlassCard,Money,ScreenHeader,SectionTitle,Pill,useResponsivePage} from '@/components/UI';

export default function Dashboard(){
  const[d,setD]=useState<any>({}),[loading,setLoading]=useState(false);const{user}=useSession();const{colors}=useTheme();const page=useResponsivePage(true);
  const load=async()=>{setLoading(true);try{setD(await api('/dashboard'))}finally{setLoading(false)}};useFocusEffect(useCallback(()=>{load()},[]));
  const currency=user?.business?.currency||APP_CONFIG.businessDefaults.currency;
  const trend=useMemo(()=>{const map=new Map<string,{income:number;expense:number}>();(d.monthlyTrend||[]).forEach((x:any)=>{const k=`${x._id.y}-${String(x._id.m).padStart(2,'0')}`;const v=map.get(k)||{income:0,expense:0};if(x._id.type==='INCOME')v.income=x.total;else v.expense=x.total;map.set(k,v)});return [...map.entries()].slice(-6)},[d.monthlyTrend]);
  const maxTrend=Math.max(1,...trend.flatMap(([,v])=>[v.income,v.expense]));
  return <AppBackground><ScrollView style={{flex:1}} contentContainerStyle={[s.content,page]} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} tintColor={colors.primary}/>}>
    <ScreenHeader title={`Good day, ${user?.name?.split(' ')[0]||'there'}`} subtitle={user?.business?.name||`Your ${APP_CONFIG.name} workspace`} right={<TouchableOpacity onPress={()=>router.push('/profile')} style={[s.profileButton,{backgroundColor:colors.surfaceStrong,borderColor:colors.borderStrong}]}><SmartImage kind="avatar" uri={user?.profilePictureUrl} size={44} fallbackText={user?.name||'T'} bordered={false}/><View style={[s.secureDot,{backgroundColor:colors.success,borderColor:colors.surfaceStrong}]}/></TouchableOpacity>}/>
    <View style={[s.hero,{backgroundColor:colors.primary2,borderColor:colors.borderStrong}]}><View style={StyleSheet.absoluteFill}><View style={[s.orb,{backgroundColor:colors.accent}]}/></View><Text style={[s.kicker,typography.medium,{color:colors.heroTextMuted}]}>{APP_CONFIG.copy.dashboardPosition.toUpperCase()}</Text><Text style={[s.heroMoney,typography.medium,{color:colors.heroText}]}>{currency} {Number(d.cashPosition||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}</Text><Text style={[s.heroSub,typography.regular,{color:colors.heroTextMuted}]}>Income less recorded expenses</Text><View style={s.heroRow}><HeroMini label="This month income" value={d.thisMonth?.income||0} currency={currency}/><HeroMini label="This month spend" value={d.thisMonth?.expenses||0} currency={currency}/></View></View>
    <View style={s.grid}><Metric label="Total income" value={d.income} currency={currency} icon="arrow-down-circle-outline" tone="income"/><Metric label="Total expenses" value={d.expenses} currency={currency} icon="arrow-up-circle-outline" tone="expense"/><Metric label="Net profit" value={d.profit} currency={currency} icon="trending-up-outline"/><Metric label="Receivables" value={d.unpaidInvoices} currency={currency} icon="time-outline"/></View>
    <SectionTitle title="Cashflow trend" subtitle="Income vs expenses • last six months"/>
    <GlassCard>{trend.length?<View style={s.chart}>{trend.map(([k,v])=><View key={k} style={s.month}><View style={s.bars}><View style={[s.bar,{height:Math.max(5,74*v.income/maxTrend),backgroundColor:colors.success}]}/><View style={[s.bar,{height:Math.max(5,74*v.expense/maxTrend),backgroundColor:colors.danger}]}/></View><Text style={[s.monthText,{color:colors.textMuted}]}>{new Date(`${k}-01`).toLocaleString('en',{month:'short'})}</Text></View>)}</View>:<Text style={{color:colors.textMuted}}>Record transactions to see your monthly trend.</Text>}<View style={s.legend}><Legend color={colors.success} text="Income"/><Legend color={colors.danger} text="Expenses"/></View></GlassCard>
    <SectionTitle title="Invoice health" subtitle="What customers still owe you"/>
    <GlassCard><View style={s.invoiceHealth}><View><Text style={[s.bigCount,{color:colors.text}]}>{d.unpaidCount||0}</Text><Text style={[s.small,{color:colors.textMuted}]}>open invoices</Text></View><View style={[s.divider,{backgroundColor:colors.border}]}/><View><Text style={[s.bigCount,{color:(d.overdueCount||0)>0?colors.danger:colors.text}]}>{d.overdueCount||0}</Text><Text style={[s.small,{color:colors.textMuted}]}>overdue invoices</Text></View><View style={{flex:1,alignItems:'flex-end'}}><Pill text={(d.overdueCount||0)>0?'Needs attention':'Healthy'} tone={(d.overdueCount||0)>0?'red':'green'}/></View></View></GlassCard>
    <SectionTitle title="Top expense categories" subtitle="Where your money is going"/>
    <GlassCard>{(d.topExpenseCategories||[]).length?(d.topExpenseCategories||[]).map((x:any,i:number)=>{const max=(d.topExpenseCategories?.[0]?.total||1);return <View key={x.category} style={[s.cat,i>0?{borderTopWidth:1,borderTopColor:colors.border}:undefined]}><View style={{flex:1}}><View style={s.catLine}><Text style={[s.catName,{color:colors.text}]}>{x.category}</Text><Money value={x.total} currency={currency} size="sm"/></View><View style={[s.track,{backgroundColor:colors.surfaceMuted}]}><View style={[s.trackFill,{backgroundColor:colors.primary,width:`${Math.max(8,Math.min(100,x.total/max*100))}%` as any}]}/></View></View></View>}):<Text style={{color:colors.textMuted}}>Add expenses to see category insights.</Text>}</GlassCard>
    {(d.recentTransactions||[]).length?<><SectionTitle title="Recent activity" subtitle="Latest ledger movements"/><GlassCard>{d.recentTransactions.slice(0,4).map((x:any,i:number)=><View key={x._id} style={[s.recent,i>0?{borderTopWidth:1,borderTopColor:colors.border}:undefined]}><View style={[s.activityIcon,{backgroundColor:x.type==='INCOME'?colors.successSoft:colors.dangerSoft}]}><Ionicons name={x.type==='INCOME'?'arrow-down':'arrow-up'} size={17} color={x.type==='INCOME'?colors.success:colors.danger}/></View><View style={{flex:1}}><Text style={[s.catName,{color:colors.text}]}>{x.category}</Text><Text style={[s.small,{color:colors.textMuted}]}>{new Date(x.date).toLocaleDateString()} • {x.paymentMethod}</Text></View><Money value={x.amount} currency={currency} size="sm" tone={x.type==='INCOME'?'income':'expense'}/></View>)}</GlassCard></>:null}
    <Text style={[s.footer,typography.regular,{color:colors.textSoft}]}>{APP_CONFIG.poweredBy} • {APP_CONFIG.tagline}</Text>
  </ScrollView></AppBackground>
}
function Metric({label,value,currency,icon,tone}:{label:string;value:number;currency:string;icon:any;tone?:'income'|'expense'}){const{colors}=useTheme();return <GlassCard style={s.metric}><View style={[s.metricIcon,{backgroundColor:tone==='expense'?colors.dangerSoft:colors.accentSoft}]}><Ionicons name={icon} size={20} color={tone==='expense'?colors.danger:colors.primary}/></View><Text style={[s.metricLabel,{color:colors.textMuted}]}>{label}</Text><Money value={value||0} currency={currency} tone={tone}/></GlassCard>}
function HeroMini({label,value,currency}:{label:string;value:number;currency:string}){const{colors}=useTheme();return <View style={[s.heroMini,{backgroundColor:colors.heroGlass,borderColor:colors.heroGlassBorder}]}><Text style={[s.heroMiniLabel,{color:colors.heroTextMuted}]}>{label}</Text><Text style={[s.heroMiniValue,{color:colors.heroText}]}>{currency} {Number(value||0).toLocaleString(undefined,{maximumFractionDigits:0})}</Text></View>}
function Legend({color,text}:{color:string;text:string}){const{colors}=useTheme();return <View style={{flexDirection:'row',alignItems:'center',gap:5}}><View style={{width:8,height:8,borderRadius:4,backgroundColor:color}}/><Text style={{fontSize:10,color:colors.textMuted,fontWeight:'500'}}>{text}</Text></View>}
const s=StyleSheet.create({content:{padding:20,paddingTop:58,paddingBottom:118},profileButton:{width:46,height:46,borderRadius:16,borderWidth:1,alignItems:'center',justifyContent:'center'},profileImage:{width:44,height:44,borderRadius:15},secureDot:{position:'absolute',right:-2,bottom:-2,width:13,height:13,borderRadius:7,borderWidth:2},hero:{borderRadius:30,padding:24,overflow:'hidden',borderWidth:1},orb:{position:'absolute',width:180,height:180,borderRadius:90,right:-70,top:-90,opacity:.18},kicker:{fontSize:10,letterSpacing:1.7},heroMoney:{fontSize:35,letterSpacing:-1.4,marginTop:10},heroSub:{marginTop:5,fontSize:12},heroRow:{flexDirection:'row',gap:10,marginTop:22},heroMini:{flex:1,borderWidth:1,borderRadius:16,padding:12},heroMiniLabel:{fontSize:9},heroMiniValue:{fontSize:13,marginTop:4},grid:{flexDirection:'row',flexWrap:'wrap',gap:12,marginTop:14},metric:{width:'48%',minHeight:130,justifyContent:'space-between'},metricIcon:{width:40,height:40,borderRadius:14,alignItems:'center',justifyContent:'center'},metricLabel:{fontSize:11,fontWeight:'500',marginTop:10},chart:{height:105,flexDirection:'row',alignItems:'flex-end',justifyContent:'space-around'},month:{alignItems:'center',flex:1},bars:{height:78,flexDirection:'row',alignItems:'flex-end',gap:3},bar:{width:8,borderRadius:5,minHeight:5},monthText:{fontSize:9,fontWeight:'500',marginTop:6},legend:{flexDirection:'row',gap:14,justifyContent:'flex-end',marginTop:8},invoiceHealth:{flexDirection:'row',alignItems:'center',gap:18},bigCount:{fontSize:26,fontWeight:'500'},small:{fontSize:10,marginTop:2},divider:{width:1,height:38},cat:{paddingVertical:14},catLine:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},catName:{fontWeight:'500',fontSize:13},track:{height:5,borderRadius:999,overflow:'hidden',marginTop:9},trackFill:{height:'100%',borderRadius:999},recent:{flexDirection:'row',alignItems:'center',gap:11,paddingVertical:12},activityIcon:{width:38,height:38,borderRadius:13,alignItems:'center',justifyContent:'center'},footer:{textAlign:'center',fontSize:10,marginTop:28}});
