import {useCallback,useMemo,useState} from 'react';
import {Alert,ScrollView,StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import {useFocusEffect} from 'expo-router';
import * as DocumentPicker from 'expo-document-picker';
import {Ionicons} from '@expo/vector-icons';
import {api,uploadAsset,deleteUploadedAsset} from '@/lib/api';
import {openStoredAttachment} from '@/lib/files';
import {APP_CONFIG,PAYMENT_METHODS,TRANSACTION_CATEGORIES,VAT_TREATMENTS} from '@/config/app';
import {typography,useTheme} from '@/lib/theme';
import {AppBackground,Button,ChoiceChips,DetailModal,EmptyState,Field,GlassCard,InfoRow,Money,ScreenHeader,SelectField,useResponsivePage} from '@/components/UI';
import {useSession} from '@/lib/session';

export default function Transactions(){
  const[list,setList]=useState<any[]>([]),[parties,setParties]=useState<any[]>([]),[show,setShow]=useState(false),[selected,setSelected]=useState<any>(null),[filter,setFilter]=useState('ALL'),[periodFilter,setPeriodFilter]=useState('ALL'),[categoryFilter,setCategoryFilter]=useState('ALL'),[paymentFilter,setPaymentFilter]=useState('ALL');
  const[type,setType]=useState<'INCOME'|'EXPENSE'>('EXPENSE'),[amount,setAmount]=useState(''),[category,setCategory]=useState<string>(TRANSACTION_CATEGORIES.EXPENSE[0]),[method,setMethod]=useState<string>(PAYMENT_METHODS[1]),[notes,setNotes]=useState(''),[partyId,setPartyId]=useState(''),[vatTreatment,setVatTreatment]=useState('TAXABLE'),[attachment,setAttachment]=useState<any>(null),[saving,setSaving]=useState(false);
  const[uploading,setUploading]=useState(false);
  const{user}=useSession();const{colors}=useTheme();const page=useResponsivePage(true);
  const load=async()=>{const[a,b]=await Promise.all([api('/transactions'),api('/parties')]);setList(a);setParties(b)};useFocusEffect(useCallback(()=>{void load().catch((e:any)=>Alert.alert('Transactions unavailable',e.message))},[]));
  async function pick(){if(uploading||saving)return;setUploading(true);try{const x=await DocumentPicker.getDocumentAsync({type:['image/*','application/pdf'],copyToCacheDirectory:true});if(!x.canceled){const next=await uploadAsset(x.assets[0] as any);if(attachment)await deleteUploadedAsset(attachment);setAttachment(next)}}catch(e:any){Alert.alert('Attachment unavailable',e.message)}finally{setUploading(false)}}
  function resetForm(){setAmount('');setNotes('');setPartyId('');setAttachment(null);setVatTreatment('TAXABLE')}
  async function save(){if(uploading||saving)return;if(!amount||Number(amount)<=0)return Alert.alert('Amount required','Enter an amount greater than zero.');setSaving(true);try{await api('/transactions',{method:'POST',headers:{'Idempotency-Key':`${Date.now()}-${Math.random()}`},body:JSON.stringify({type,amount:Number(amount),category,paymentMethod:method,notes:notes.trim()||undefined,date:new Date(),partyId:partyId||undefined,vatTreatment,vatPercent:user?.business?.vatPercent||APP_CONFIG.businessDefaults.vatPercent,attachment:attachment||undefined})});setShow(false);resetForm();await load()}catch(e:any){Alert.alert('Transaction not saved',e.message)}finally{setSaving(false)}}
  async function remove(x:any){Alert.alert('Delete transaction','This permanently removes this ledger entry. Continue?',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:async()=>{try{await api(`/transactions/${x._id}`,{method:'DELETE',headers:{'Idempotency-Key':`${Date.now()}-${Math.random()}`}});setSelected(null);await load()}catch(e:any){Alert.alert('Delete failed',e.message)}}}])}
  const currency=user?.business?.currency||APP_CONFIG.businessDefaults.currency;
  const shown=useMemo(()=>list.filter(x=>{if(filter!=='ALL'&&x.type!==filter)return false;if(periodFilter==='MONTH'){const d=new Date(x.date),n=new Date();if(d.getFullYear()!==n.getFullYear()||d.getMonth()!==n.getMonth())return false}if(categoryFilter!=='ALL'&&x.category!==categoryFilter)return false;if(paymentFilter!=='ALL'&&x.paymentMethod!==paymentFilter)return false;return true}),[list,filter,periodFilter,categoryFilter,paymentFilter]);
  const usedCategories=useMemo(()=>['ALL',...Array.from(new Set(list.map(x=>String(x.category))))],[list]);
  const summary=useMemo(()=>({income:list.filter(x=>x.type==='INCOME').reduce((s,x)=>s+Number(x.amount||0),0),expenses:list.filter(x=>x.type==='EXPENSE').reduce((s,x)=>s+Number(x.amount||0),0)}),[list]);
  const catOptions=TRANSACTION_CATEGORIES[type].map(x=>({key:x,label:x}));
  return <AppBackground><ScrollView style={{flex:1}} contentContainerStyle={[s.content,page]} keyboardShouldPersistTaps="handled">
    <ScreenHeader title={APP_CONFIG.copy.transactionsTitle} subtitle={APP_CONFIG.copy.transactionsSubtitle} right={<TouchableOpacity style={[s.add,{backgroundColor:colors.primary}]} onPress={()=>setShow(!show)}><Ionicons name={show?'close':'add'} size={24} color={colors.onPrimary}/></TouchableOpacity>}/>
    <View style={s.summary}><GlassCard style={s.sumCard}><Text style={[s.sumLabel,typography.regular,{color:colors.textMuted}]}>Money in</Text><Money value={summary.income} currency={currency} tone="income"/></GlassCard><GlassCard style={s.sumCard}><Text style={[s.sumLabel,typography.regular,{color:colors.textMuted}]}>Money out</Text><Money value={summary.expenses} currency={currency} tone="expense"/></GlassCard></View>
    {show&&<GlassCard style={{gap:14,marginBottom:16}}><ChoiceChips wrap options={[{key:'EXPENSE',label:'Money out'},{key:'INCOME',label:'Money in'}]} value={type} onChange={v=>{const next=v as 'INCOME'|'EXPENSE';setType(next);setCategory(next==='EXPENSE'?'General':'Sales')}}/><Field label="Amount" value={amount} onChangeText={setAmount} keyboardType="decimal-pad" placeholder="0.00"/><SelectField label="Category" value={category} options={catOptions} onChange={setCategory}/><SelectField label="Payment method" value={method} options={PAYMENT_METHODS.map(x=>({key:x,label:x}))} onChange={setMethod}/><SelectField label="Customer / supplier (optional)" value={partyId} options={[{key:'',label:'No linked contact'},...parties.map(x=>({key:x._id,label:x.name,meta:x.type==='CUSTOMER'?'Customer':'Supplier'}))]} onChange={setPartyId}/><SelectField label="VAT treatment" value={vatTreatment} options={VAT_TREATMENTS.map(x=>({key:x.key,label:x.label})) as any} onChange={setVatTreatment}/><Field label="Notes (optional)" value={notes} onChangeText={setNotes} multiline placeholder="Reference, purpose or internal note"/><Button secondary icon="attach" title={attachment?`Attached: ${attachment.name}`:'Add receipt, bill or PDF (optional)'} onPress={pick} loading={uploading} loadingTitle="Uploading attachment…" disabled={saving}/>{attachment?<View style={[s.attachment,{backgroundColor:colors.surfaceMuted,borderColor:colors.border}]}><Ionicons name="document-attach-outline" size={18} color={colors.primary}/><Text style={[typography.medium,{flex:1,color:colors.text,fontSize:12}]} numberOfLines={1}>{attachment.name}</Text><TouchableOpacity disabled={uploading||saving} onPress={async()=>{await deleteUploadedAsset(attachment);setAttachment(null)}}><Ionicons name="close-circle" size={20} color={colors.textMuted}/></TouchableOpacity></View>:null}<Button title="Save transaction" onPress={save} loading={saving} loadingTitle="Saving transaction…" disabled={uploading}/></GlassCard>}
    <View style={s.filters}><Filter text="All" active={filter==='ALL'} onPress={()=>setFilter('ALL')}/><Filter text="Money in" active={filter==='INCOME'} onPress={()=>setFilter('INCOME')}/><Filter text="Money out" active={filter==='EXPENSE'} onPress={()=>setFilter('EXPENSE')}/></View>
    <GlassCard style={{gap:11,marginBottom:12}}><SelectField label="Period" value={periodFilter} options={[{key:'ALL',label:'All time'},{key:'MONTH',label:'This month'}]} onChange={setPeriodFilter}/><SelectField label="Category filter" value={categoryFilter} options={usedCategories.map(x=>({key:x,label:x==='ALL'?'All categories':x}))} onChange={setCategoryFilter}/><SelectField label="Payment filter" value={paymentFilter} options={[{key:'ALL',label:'All payment methods'},...PAYMENT_METHODS.map(x=>({key:x,label:x}))]} onChange={setPaymentFilter}/></GlassCard>
    <GlassCard>{shown.length?shown.map((x,i)=><TouchableOpacity key={x._id} activeOpacity={.72} onPress={()=>setSelected(x)} style={[s.item,i>0?{borderTopWidth:1,borderTopColor:colors.border}:undefined]}><View style={[s.icon,{backgroundColor:x.type==='INCOME'?colors.successSoft:colors.dangerSoft}]}><Ionicons name={x.type==='INCOME'?'arrow-down':'arrow-up'} size={18} color={x.type==='INCOME'?colors.success:colors.danger}/></View><View style={{flex:1}}><View style={{flexDirection:'row',alignItems:'center',gap:7}}><Text style={[s.name,typography.medium,{color:colors.text}]}>{x.category}</Text>{x.attachment?<Ionicons name="attach" size={13} color={colors.textMuted}/>:null}</View><Text style={[s.meta,typography.regular,{color:colors.textMuted}]}>{new Date(x.date).toLocaleDateString()} • {x.paymentMethod}{x.partyName?` • ${x.partyName}`:''}</Text></View><View style={{alignItems:'flex-end',gap:4}}><Money value={x.amount} currency={currency} size="sm" tone={x.type==='INCOME'?'income':'expense'}/><Ionicons name="chevron-forward" size={15} color={colors.textSoft}/></View></TouchableOpacity>):<EmptyState icon="swap-horizontal-outline" title="Your ledger is ready" body="Tap + to record the first business movement."/>}</GlassCard>
    <Text style={[s.hint,typography.regular,{color:colors.textSoft}]}>Tap any entry for VAT, notes, linked contact and supporting documents.</Text>
  </ScrollView>
  <DetailModal visible={!!selected} onClose={()=>setSelected(null)} title={selected?.category||'Transaction'} subtitle={selected?`${selected.type==='INCOME'?'Money in':'Money out'} • ${new Date(selected.date).toLocaleDateString()}`:undefined} footer={selected?<Button danger secondary icon="trash-outline" title="Delete transaction" onPress={()=>remove(selected)} compact/>:undefined}>
    {selected?<><View style={[s.detailAmount,{backgroundColor:selected.type==='INCOME'?colors.successSoft:colors.dangerSoft}]}><Text style={[s.detailKicker,typography.medium,{color:selected.type==='INCOME'?colors.success:colors.danger}]}>{selected.type==='INCOME'?'MONEY IN':'MONEY OUT'}</Text><Money value={selected.amount} currency={currency} size="lg" tone={selected.type==='INCOME'?'income':'expense'}/></View><InfoRow label="Category" value={selected.category}/><InfoRow label="Date" value={new Date(selected.date).toLocaleString()}/><InfoRow label="Payment method" value={selected.paymentMethod}/><InfoRow label="Customer / supplier (optional)" value={selected.partyName||'—'}/><InfoRow label="VAT treatment" value={String(selected.vatTreatment||'TAXABLE').replace('_',' ')}/><InfoRow label="VAT amount" value={<Money value={selected.vatAmount||0} currency={currency} size="sm"/>}/><InfoRow label="Notes (optional)" value={selected.notes||'—'}/>{selected.attachment?<View style={{marginTop:16}}><Button secondary icon="document-attach-outline" title={`Open ${selected.attachment.name||'attachment'}`} onPress={async()=>{try{await openStoredAttachment(selected.attachment)}catch(e:any){Alert.alert('Attachment unavailable',e.message)}}}/></View>:null}</>:null}
  </DetailModal></AppBackground>
}
function Filter({text,active,onPress}:{text:string;active:boolean;onPress:()=>void}){const{colors}=useTheme();return <TouchableOpacity onPress={onPress} style={[s.filter,{backgroundColor:active?colors.primary:colors.surfaceStrong,borderColor:active?colors.primary:colors.border}]}><Text style={[typography.medium,{fontSize:11,color:active?colors.onPrimary:colors.textMuted}]}>{text}</Text></TouchableOpacity>}
const s=StyleSheet.create({content:{padding:20,paddingTop:58,paddingBottom:118},add:{width:46,height:46,borderRadius:16,alignItems:'center',justifyContent:'center'},summary:{flexDirection:'row',gap:12,marginBottom:14},sumCard:{flex:1,minHeight:86,justifyContent:'space-between'},sumLabel:{fontSize:11},attachment:{borderWidth:1,borderRadius:13,padding:10,flexDirection:'row',alignItems:'center',gap:9},filters:{flexDirection:'row',gap:8,marginBottom:12},filter:{borderWidth:1,borderRadius:999,paddingHorizontal:13,paddingVertical:8},item:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:14},icon:{width:42,height:42,borderRadius:14,alignItems:'center',justifyContent:'center'},name:{fontSize:14},meta:{fontSize:11,marginTop:4},hint:{fontSize:10,lineHeight:16,textAlign:'center',marginTop:14,paddingHorizontal:20},detailAmount:{borderRadius:20,padding:18,marginBottom:10},detailKicker:{fontSize:10,letterSpacing:1.4,marginBottom:5}});
