import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import compression from 'compression';
import path from 'node:path';
import mongoose from 'mongoose';
import { env } from './config/env.js';
import { globalLimiter } from './middleware/security.js';
import {ensureStorageReady} from './services/storage.js';
import auth from './routes/auth.js';
import parties from './routes/parties.js';
import transactions from './routes/transactions.js';
import invoices from './routes/invoices.js';
import dashboard from './routes/dashboard.js';
import profile from './routes/profile.js';
import uploads from './routes/uploads.js';
import reports from './routes/reports.js';
import admin from './routes/admin.js';
import media from './routes/media.js';
export const app=express();
app.set('trust proxy',1);app.use(helmet({crossOriginResourcePolicy:{policy:'cross-origin'}}));app.use(cors({origin:true,credentials:false}));app.use(compression());app.use(globalLimiter);app.use(express.json({limit:'1mb'}));app.use(express.urlencoded({extended:false,limit:'1mb'}));
if(env.STORAGE_DRIVER==='local')app.use('/uploads',express.static(path.resolve(env.UPLOAD_DIR),{fallthrough:false,maxAge:'1h'}));
app.use('/media',media);
app.get('/health',(_req,res)=>res.json({ok:true,service:'tekbooks-api',version:'1.0.9-hotfix2',time:new Date().toISOString()}));
app.get('/ready',async(_req,res)=>{try{if(mongoose.connection.readyState!==1)throw new Error('Database is not connected');await mongoose.connection.db?.admin().ping();const storage=await ensureStorageReady(false);res.json({ok:true,database:'ready',storage:{driver:storage.driver,ready:true}})}catch(error:any){res.status(503).json({ok:false,message:error?.message||'Service not ready'})}});
app.use('/api/auth',auth);app.use('/api/parties',parties);app.use('/api/transactions',transactions);app.use('/api/invoices',invoices);app.use('/api/dashboard',dashboard);app.use('/api/profile',profile);app.use('/api/uploads',uploads);app.use('/api/reports',reports);app.use('/api/admin',admin);
app.use((_req,res)=>res.status(404).json({message:'Route not found'}));
app.use((err:any,_req:any,res:any,_next:any)=>{console.error(err);res.status(err?.status||500).json({message:env.NODE_ENV==='production'?'Unexpected server error':err?.message||'Unexpected server error'});});
