import { Router } from 'express';
import { z } from 'zod';
import { Transaction, Party } from '../models/index.js';
import { requireAuth } from '../middleware/auth.js';
import { idempotency } from '../middleware/security.js';
import {removeStoredFile} from '../services/storage.js';
const r=Router();r.use(requireAuth);r.use(idempotency);
const attachment=z.object({name:z.string().optional(),url:z.string().optional(),key:z.string().optional(),mimeType:z.string().optional(),size:z.number().optional()}).passthrough().optional();
const schema=z.object({type:z.enum(['INCOME','EXPENSE']),amount:z.coerce.number().positive(),category:z.string().min(1),paymentMethod:z.string().min(1),notes:z.string().optional(),date:z.coerce.date(),partyId:z.string().optional().or(z.literal('')),vatTreatment:z.enum(['TAXABLE','ZERO_RATED','EXEMPT']).default('TAXABLE'),vatPercent:z.coerce.number().min(0).max(100).default(5),attachment});
function vat(amount:number,treatment:string,percent:number){return treatment==='TAXABLE'&&percent>0?(amount*percent)/(100+percent):0}
r.get('/',async(req,res)=>{const q:any={userId:req.user._id};if(req.query.type)q.type=req.query.type;if(req.query.category)q.category=req.query.category;if(req.query.paymentMethod)q.paymentMethod=req.query.paymentMethod;if(req.query.month){const[y,m]=String(req.query.month).split('-').map(Number);if(!y||!m||m<1||m>12)return res.status(400).json({message:'Month filter must use YYYY-MM format.'});q.date={$gte:new Date(Date.UTC(y,m-1,1)),$lt:new Date(Date.UTC(y,m,1))}}res.json(await Transaction.find(q).sort({date:-1,createdAt:-1}).limit(500).lean())});
r.post('/',async(req,res)=>{const p=schema.safeParse(req.body);if(!p.success)return res.status(400).json({message:'Transaction details are invalid.',issues:p.error.flatten()});let partyName='';if(p.data.partyId){const party=await Party.findOne({_id:p.data.partyId,userId:req.user._id});if(!party)return res.status(400).json({message:'The selected customer/supplier no longer exists.'});partyName=party.name}const vatAmount=vat(p.data.amount,p.data.vatTreatment,p.data.vatPercent);res.status(201).json(await Transaction.create({...p.data,partyId:p.data.partyId||undefined,partyName,vatAmount,userId:req.user._id}))});
r.put('/:id',async(req,res)=>{const p=schema.partial().safeParse(req.body);if(!p.success)return res.status(400).json({message:'Transaction details are invalid.',issues:p.error.flatten()});const x:any=await Transaction.findOne({_id:req.params.id,userId:req.user._id});if(!x)return res.status(404).json({message:'Transaction not found'});const oldAttachment=x.attachment?.toObject?.()||x.attachment;let partyName=x.partyName||'';if(p.data.partyId!==undefined){if(p.data.partyId){const party=await Party.findOne({_id:p.data.partyId,userId:req.user._id});if(!party)return res.status(400).json({message:'The selected customer/supplier no longer exists.'});partyName=party.name}else partyName=''}Object.assign(x,p.data);if(p.data.partyId!==undefined)x.partyId=p.data.partyId||undefined;x.partyName=partyName;x.vatAmount=vat(Number(x.amount),String(x.vatTreatment),Number(x.vatPercent));await x.save();if(p.data.attachment&&oldAttachment&&String(oldAttachment.key||oldAttachment.url)!==String(p.data.attachment.key||p.data.attachment.url))removeStoredFile(oldAttachment).catch(()=>{});res.json(x)});
r.delete('/:id',async(req,res)=>{const x:any=await Transaction.findOneAndDelete({_id:req.params.id,userId:req.user._id});if(!x)return res.status(404).json({message:'Transaction not found'});if(x.attachment)removeStoredFile(x.attachment).catch(()=>{});res.status(204).end()});
export default r;
