$ErrorActionPreference = 'Stop'

function Read-SecretText([string]$Prompt) {
  $secure = Read-Host $Prompt -AsSecureString
  $pointer = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
  try {
    return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($pointer)
  }
  finally {
    [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($pointer)
  }
}

function New-RandomSecret {
  $bytes = New-Object byte[] 48
  [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
  return ([Convert]::ToBase64String($bytes)).TrimEnd('=').Replace('+', '-').Replace('/', '_')
}

function Assert-OneLine([string]$Name, [string]$Value) {
  if ([string]::IsNullOrWhiteSpace($Value) -or $Value.Contains("`r") -or $Value.Contains("`n")) {
    throw "$Name is empty or invalid."
  }
}

$repoRoot = Split-Path -Parent $PSScriptRoot
$envPath = Join-Path $repoRoot 'backend\.env'

Write-Host ''
Write-Host 'TekBooks cloud-backed local setup' -ForegroundColor Cyan
Write-Host 'This makes local development use Atlas, private S3, and Resend.'
Write-Host 'npm run dev will still detect the active home/company Wi-Fi automatically.'
Write-Host ''

$mongoUri = Read-SecretText 'MongoDB Atlas connection string (input is hidden)'
$databaseName = (Read-Host 'Local database name [tekbooks_dev]').Trim()
if (-not $databaseName) { $databaseName = 'tekbooks_dev' }
$s3Region = (Read-Host 'AWS S3 region from your sir (example: ap-south-1)').Trim()
$s3Bucket = (Read-Host 'AWS S3 bucket name from your sir').Trim()
$s3AccessKeyId = (Read-Host 'AWS S3 access key ID from your sir').Trim()
$s3SecretAccessKey = Read-SecretText 'AWS S3 secret access key from your sir (input is hidden)'
$resendKey = Read-SecretText 'Resend API key beginning re_ (input is hidden)'
$resendFrom = (Read-Host 'Resend sender [TekBooks <onboarding@resend.dev>]').Trim()
if (-not $resendFrom) { $resendFrom = 'TekBooks <onboarding@resend.dev>' }

Assert-OneLine 'MONGODB_URI' $mongoUri
Assert-OneLine 'S3_REGION' $s3Region
Assert-OneLine 'S3_BUCKET' $s3Bucket
Assert-OneLine 'S3_ACCESS_KEY_ID' $s3AccessKeyId
Assert-OneLine 'S3_SECRET_ACCESS_KEY' $s3SecretAccessKey
Assert-OneLine 'RESEND_API_KEY' $resendKey
Assert-OneLine 'RESEND_FROM' $resendFrom
if ($mongoUri -notmatch '^mongodb(?:\+srv)?://') { throw 'MONGODB_URI must start with mongodb:// or mongodb+srv://.' }
if ($databaseName -notmatch '^[a-zA-Z0-9_-]+$') { throw 'The database name can contain only letters, numbers, underscore, and hyphen.' }
if ($resendKey -notmatch '^re_') { throw 'The Resend API key must start with re_.' }
if ($s3Region -notmatch '^[a-z]{2}(?:-gov)?-[a-z]+-\d$') { throw 'S3_REGION does not look valid. Example: ap-south-1 or us-east-1.' }
if ($s3Bucket.Length -lt 3 -or $s3Bucket.Length -gt 63 -or $s3Bucket -notmatch '^[a-z0-9][a-z0-9.-]*[a-z0-9]$' -or $s3Bucket -match '\.\.') { throw 'S3_BUCKET must be the exact lowercase AWS bucket name.' }
if ($s3AccessKeyId -notmatch '^[A-Z0-9]{16,128}$') { throw 'S3_ACCESS_KEY_ID does not look valid.' }
if ($s3SecretAccessKey.Length -lt 16) { throw 'S3_SECRET_ACCESS_KEY does not look valid.' }

if (Test-Path -LiteralPath $envPath) {
  $answer = (Read-Host 'backend/.env already exists. Back it up and replace it? [y/N]').Trim()
  if ($answer -notmatch '^(y|yes)$') {
    Write-Host 'No file was changed.' -ForegroundColor Yellow
    exit 0
  }
  $stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
  Copy-Item -LiteralPath $envPath -Destination "$envPath.backup-$stamp"
  Write-Host "Backup created: backend/.env.backup-$stamp"
}

$lines = @(
  '# Generated by npm run configure:local. This file is git-ignored.'
  'NODE_ENV=development'
  'PORT=4000'
  'APP_BASE_URL=http://localhost:4000'
  'MOBILE_SCHEME=tekbooks'
  'CORS_ORIGINS='
  "MONGODB_URI=$mongoUri"
  "MONGODB_DB_NAME=$databaseName"
  "JWT_SECRET=$(New-RandomSecret)"
  "MEDIA_SIGNING_SECRET=$(New-RandomSecret)"
  'MEDIA_URL_TTL_SECONDS=86400'
  'MEDIA_ALLOW_LEGACY_SIGNATURES=false'
  'ALLOW_EXPO_GO_DEVICE_BYPASS=false'
  "ADMIN_API_KEY=$(New-RandomSecret)"
  "RESEND_API_KEY=$resendKey"
  "RESEND_FROM=$resendFrom"
  'EMAIL_DEV_LOG_CODES=false'
  'STORAGE_DRIVER=s3'
  'STORAGE_PUBLIC_MODE=proxy'
  'STORAGE_KEY_PREFIX=users'
  'STORAGE_AUTO_CREATE_BUCKET=false'
  'STORAGE_VALIDATE_ON_STARTUP=true'
  'UPLOAD_DIR=uploads'
  'MAX_UPLOAD_MB=10'
  "S3_REGION=$s3Region"
  "S3_BUCKET=$s3Bucket"
  "S3_ACCESS_KEY_ID=$s3AccessKeyId"
  "S3_SECRET_ACCESS_KEY=$s3SecretAccessKey"
  'S3_UPLOAD_URL_TTL_SECONDS=300'
  'S3_DOWNLOAD_URL_TTL_SECONDS=300'
  'EXPO_PUSH_ACCESS_TOKEN='
)

[IO.File]::WriteAllText($envPath, (($lines -join "`r`n") + "`r`n"), (New-Object Text.UTF8Encoding($false)))
$mongoUri = $null
$s3AccessKeyId = $null
$s3SecretAccessKey = $null
$resendKey = $null

Write-Host ''
Write-Host 'backend/.env is ready.' -ForegroundColor Green
Write-Host 'Next run: npm run system:check -- --email=YOUR_EMAIL'
Write-Host 'Then run: npm run dev'
